### ISSUE TITLE
$.murabanners is undefined CF error after restarting CF

### ISSUE THREAD

**Issue by ronnieduke** [stevewithington/MuraBanners#2]
This seems to happen after CF has been restarted. An appreload fixes it though. Any thoughts on how to keep this from happening after a CF restart?

**Comment by stevewithington** [comment]
@ronnieduke, think i fixed the issue. let me know if you run into it again after updating. thanks!

**Comment by ronnieduke** [comment]
@stevewithington , I installed the update and it appears this is still happening after restarting CF on the server.

**Comment by ronnieduke** [comment]
@stevewithington, My app is still having trouble with this... Whenever I restart CF 9, I get the error message on any page that has $.murabanners referenced in the page template. Let me know if there is anything specific you want me to try.

Thanks!

**Comment by stevewithington** [comment]
@ronnieduke, How are you including it? Do you have a code sample that I can try to test with?

**Comment by ronnieduke** [comment]
@stevewithington, Here is a code snippet from a display template:

<div id="headerImg">#$.muraBanners.dspBanner(height=230,width=580)#</div>

Hit me up offline if you wanna run through a demo.

**Comment by stevewithington** [comment]
@ronnieduke,

Sorry for the delay...however, I just tested with the same exact code by placing it in a layout template, stopped CF, restarted it, and hit the page again and it came up without any problem.  I'm on CF10 though, but that shouldn't really make a difference in this case.

In the mean time, as a workaround for you, I would recommend wrapping your output with something like this to prevent the error from being thrown:

``` coldfusion
<cfif StructKeyExists($, 'muraBanners')>
<div id="headerImg">#$.muraBanners.dspBanner(height=230,width=580)#</div>
</cfif>
```

Wish I could reproduce the error on my end, but I just can't.

**Comment by ronnieduke** [comment]
@stevewithington - Thanks for taking the time to look into this. That's super weird. I will try your suggestion as a workaround for now.

Thanks!
